# Homebrew formula for forgeo.
#
# This file is generated by the release pipeline in the forgeo repository
# (.github/workflows/ci.yml, publish-homebrew job): every new tag vX.Y.Z
# downloads the prebuilt binaries, computes their sha256 and updates this
# formula. Do not edit by hand; re-run the pipeline instead.

class Forgeo < Formula
  desc "A scheduled software forgeo: executes backlog tasks on main, refactors when idle, and writes BLOCKER.md when it needs human input."
  homepage "https://forgeo.org"
  version "0.11.0"
  license "MIT"

  url "https://github.com/lucaGazzola/forgeo/releases/download/v0.11.0/forgeo-linux-amd64"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.11.0/forgeo-darwin-arm64"
      sha256 "0e546098de8aa4d2940332aee70f3763e27eeccd03d453d3363db503a24bde03"
    else
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.11.0/forgeo-darwin-amd64"
      sha256 "03351d11c1241328303988799a41d55ef566ad02c22d5539873d5c35d73ff8b8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.11.0/forgeo-linux-amd64"
      sha256 "8909a4a5e15385dc96baa9912e67146a880166a7aeb04bd3fa3da7544500aca8"
    end
  end

  def install
    binary = Pathname.glob("forgeo-*").first
    bin.install binary => "forgeo"
  end

  test do
    assert_match "forgeo #{version}", shell_output("#{bin}/forgeo --version")
  end
end
