# Homebrew formula for forgeo.
#
# This file is generated by the release pipeline in the forgeo repository
# (.github/workflows/ci.yml, publish-homebrew job): every new tag vX.Y.Z
# downloads the prebuilt binaries, computes their sha256 and updates this
# formula. Do not edit by hand; re-run the pipeline instead.

class Forgeo < Formula
  desc "A scheduled software forgeo: executes backlog tasks on main, refactors when idle, and writes BLOCKER.md when it needs human input."
  homepage "https://forgeo.org"
  version "0.5.0"
  license "MIT"

  url "https://github.com/lucaGazzola/forgeo/releases/download/v0.5.0/forgeo-linux-amd64"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.5.0/forgeo-darwin-arm64"
      sha256 "3321622cdb3ae501f488a6e4a738a57eb8b3333d2ee057eab633ebd8bbbc75dc"
    else
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.5.0/forgeo-darwin-amd64"
      sha256 "4b77ec62d7a1e7d4f366ff9ea2f9cb7f8d7512235d22f15dcf0bf730cf2391d8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.5.0/forgeo-linux-amd64"
      sha256 "d42993c97c929f308349cf624b179e1ee6b0c75c0e4a99697f765762e66549a6"
    end
  end

  def install
    binary = Pathname.glob("forgeo-*").first
    bin.install binary => "forgeo"
  end

  test do
    assert_match "forgeo #{version}", shell_output("#{bin}/forgeo --version")
  end
end
