# Homebrew formula for forgeo.
#
# This file is generated by the release pipeline in the forgeo repository
# (.github/workflows/ci.yml, publish-homebrew job): every new tag vX.Y.Z
# downloads the prebuilt binaries, computes their sha256 and updates this
# formula. Do not edit by hand; re-run the pipeline instead.

class Forgeo < Formula
  desc "A scheduled software forgeo: executes backlog tasks on main, refactors when idle, and writes BLOCKER.md when it needs human input."
  homepage "https://forgeo.org"
  version "0.8.0"
  license "MIT"

  url "https://github.com/lucaGazzola/forgeo/releases/download/v0.8.0/forgeo-linux-amd64"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.8.0/forgeo-darwin-arm64"
      sha256 "9646bb4c87cdf54a90f93dc0e09dddc05d9b865ec2e2e11060e0cd22114b6378"
    else
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.8.0/forgeo-darwin-amd64"
      sha256 "abfa44cb868a9942cd311fc79237f5ae8c942819dc8c154d28a95cd43fb9722e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucaGazzola/forgeo/releases/download/v0.8.0/forgeo-linux-amd64"
      sha256 "b393067fab9fb8509a69db4cd22862cbac924b2eca5106805d5e68fd336cf3d0"
    end
  end

  def install
    binary = Pathname.glob("forgeo-*").first
    bin.install binary => "forgeo"
  end

  test do
    assert_match "forgeo #{version}", shell_output("#{bin}/forgeo --version")
  end
end
